FROM jenkins/jenkins:lts
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
RUN /bin/sh -c 'sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common'
RUN /bin/sh -c 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
RUN /bin/sh -c 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
RUN /bin/sh -c 'sudo apt-get update'
RUN /bin/sh -c 'sudo apt-get install docker-ce docker-ce-cli containerd.io'
RUN /bin/sh -c 'sudo usermod -aG docker jenkins'
RUN /bin/sh -c 'sudo apti-get install git'
